export const FALLBACK_PROJECTS = [
  { slug: 'edificio-altavista', title: 'Edificio Altavista', category: 'bim_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_1.png', is_published: true },
  { slug: 'centro-comercial-sur', title: 'Centro Comercial Sur', category: 'gestion_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_2.png', is_published: true },
  { slug: 'residencial-los-alpes', title: 'Residencial Los Alpes', category: 'bim_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_3.png', is_published: true },
  { slug: 'hospital-regional', title: 'Hospital Regional', category: 'bim_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_4.png', is_published: true },
  { slug: 'clinica-dentalica', title: 'Clinica Dentalica', category: 'gestion_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_5.png', is_published: true },
  { slug: 'hotel-marriot', title: 'Hotel Marriot', category: 'bim_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_6.png', is_published: true },
  { slug: 'casa-stachetti', title: 'Casa Stachetti', category: 'bim_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_7.png', is_published: true },
  { slug: 'torre-financiera', title: 'Torre Financiera', category: 'gestion_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_8.png', is_published: true },
  { slug: 'pabellon-deportivo', title: 'Pabellon Deportivo', category: 'gestion_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_9.png', is_published: true },
  { slug: 'terminal-de-buses', title: 'Terminal de Buses', category: 'bim_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_10.png', is_published: true },
  { slug: 'plaza-bicentenario', title: 'Plaza Bicentenario', category: 'gestion_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_11.png', is_published: true },
  { slug: 'campus-universitario', title: 'Campus Universitario', category: 'bim_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_12.png', is_published: true },
  { slug: 'teatro-de-las-artes', title: 'Teatro de las Artes', category: 'gestion_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_13.png', is_published: true },
  { slug: 'museo-contemporaneo', title: 'Museo Contemporaneo', category: 'bim_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_14.png', is_published: true },
  { slug: 'estadio-nacional', title: 'Estadio Nacional', category: 'bim_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_15.png', is_published: true },
  { slug: 'edificio-gubernamental', title: 'Edificio Gubernamental', category: 'gestion_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_16.png', is_published: true },
  { slug: 'aeropuerto-del-sur', title: 'Aeropuerto del Sur', category: 'gestion_ejecutado', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_17.png', is_published: true },
  { slug: 'linea-de-metro', title: 'Linea de Metro', category: 'bim_proyecto', cover_url: 'https://propuestas.dmvdigital.cl/mistudio/imgs/sketches/sketch_18.png', is_published: true },
]